workflows:
  flx-android:
    name: Flx Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Clean and get packages
        script: |
          rm -rf build .dart_tool
          flutter clean
          flutter pub get
      - name: Build APK (verbose)
        script: |
          flutter build apk --release --split-per-abi --verbose
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
